services:
  - type: web
    name: krakow-wifi
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_ADSENSE_PUBLISHER_ID
        value: ca-pub-4304502432915728
      - key: NEXT_PUBLIC_MEDIANET_CUSTOMER_ID
        sync: false
